print("# 하나만 출력합니다.")
print("Hello Python Programming...!")
print()
print("# 여러 개를 출력합니다.")
print(10, 20, 30, 40, 50)
print("안녕하세요", "저의", "이름은", "윤인성입니다")
print()
print("# 아무것도 출력하지 않습니다.")
print('--- 확인  전용선 ---')
print()
print()
print("--- 확인  전용선 ---")
print()
print()
print("이름", "나이", "지역")
print("이름 나이 지역")
print("이름\t나이\t지역")
print("윤인성\t25\t강서구")
print("윤아린\t24\t강서구")
print("구름\t3\t강서구")
print()
print(50-1+3)
print((50-20)*3)
print("안녕하세요.\n손님~! 반가워요")
print("안녕하세요. 저는 \"강중구\" 입니다.")
print("안녕하세요. 저는 \"강중구 입니다.")
print("안녕하세요. 저는 '강중구' 입니다")